name = "payment-app-by-factors-api"
main = "src/index.ts"
compatibility_date = "2025-11-17"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[kv_namespaces]]
binding = "PAYMENT_STORE"
id = "1aa0fe2331e04baa972449322c4111a9"
