# mise設定ファイル

# 必要なツールとバージョンを定義
[tools]
terraform = "1.14.3"
awscli = "2.27.41"  # AWS CLI v2
wrangler = "4.54.0"
"aqua:auth0/auth0-cli" = "latest"

[tasks.setup]
description = "ツールのインストールとProviderをセットアップ"
run = """
chmod 775 ./setup.sh
chmod 775 ./init-auth0.sh
chmod 775 ./init-aws.sh
chmod 775 ./aws/update-eventbus.sh
chmod 775 ./resource-app/setup-deploy.sh
bash ./setup.sh
"""