name = "payment-app-by-oidc"
main = "src/index.ts"
compatibility_date = "2025-11-17"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[kv_namespaces]]
binding = "PAYMENT_STORE"
id = "af72ad0c1d7c439a94e042b887672c04"
