#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
TERRAFORM_DIR="$ROOT_DIR/terraform"
OIDC_APP_DIR="$ROOT_DIR/payment-app-by-oidc"
FACTORS_APP_DIR="$ROOT_DIR/payment-app-by-factors-api"

require() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Error: '$1' command is required but was not found." >&2
    exit 1
  fi
}

ensure_prereqs() {
  require pnpm
  require terraform
  require jq
  require awk
}

install_dependencies() {
  local app_dir=$1
  if [ -f "$app_dir/package.json" ]; then
    echo "Installing dependencies in $app_dir..."
    (cd "$app_dir" && pnpm install --frozen-lockfile)
  fi
}

extract_workers_url() {
  sed -nE 's#.*(https://[[:alnum:]._-]+\.workers\.dev).*#\1#p' | head -n1
}

deploy_and_get_url() {
  local app_dir=$1
  local output

  echo "Deploying $(basename "$app_dir")..."
  if ! output=$(cd "$app_dir" && pnpm exec wrangler deploy 2>&1); then
    printf '%s\n' "$output" >&2
    exit 1
  fi

  printf '%s\n' "$output"

  local url
  url=$(printf '%s\n' "$output" | extract_workers_url)
  if [ -z "$url" ]; then
    echo "Error: Failed to detect workers.dev URL from deploy output." >&2
    exit 1
  fi

  printf '%s\n' "$url"
}

run_terraform_apply() {
  local worker_url=$1
  echo "Applying Terraform changes..."
  (
    cd "$TERRAFORM_DIR"
    terraform init -input=false
    terraform apply -auto-approve -input=false \
      -var="stepup_redirect_uris=[\"$worker_url/callback\",\"$worker_url\"]"
  )
}

read_tf_output() {
  local key=$1
  (cd "$TERRAFORM_DIR" && terraform output -json) | jq -er ".[\"$key\"].value"
}

create_kv_namespace() {
  local app_dir=$1
  local binding=$2
  local output

  echo "Creating KV namespace '$binding' for $(basename "$app_dir")..."
  if ! output=$(cd "$app_dir" && pnpm exec wrangler kv namespace create "$binding" 2>&1); then
    printf '%s\n' "$output" >&2
    exit 1
  fi
  printf '%s\n' "$output"

  local ns_id
  ns_id=$(printf '%s\n' "$output" | sed -nE 's/.*id = "([^"]+)".*/\1/p' | head -n1)
  if [ -z "$ns_id" ]; then
    echo "Error: Failed to extract KV namespace ID from wrangler output." >&2
    exit 1
  fi

  echo "Updating wrangler.toml with KV namespace ID: $ns_id"
  sed -i "s/id = \"your-kv-namespace-id\"/id = \"$ns_id\"/" "$app_dir/wrangler.toml"
  printf '%s\n' "$ns_id"
}

put_secret() {
  local app_dir=$1
  local key=$2
  local value=$3
  if [[ "$value" == *\\n* ]]; then
    printf '%b' "$value"
  else
    printf '%s' "$value"
  fi | (cd "$app_dir" && pnpm exec wrangler secret put "$key")
}

main() {
  ensure_prereqs

  install_dependencies "$OIDC_APP_DIR"
  install_dependencies "$FACTORS_APP_DIR"

  echo "Creating KV namespaces..."
  create_kv_namespace "$OIDC_APP_DIR" "PAYMENT_STORE_OIDC" > /dev/null
  create_kv_namespace "$FACTORS_APP_DIR" "PAYMENT_STORE_FACTOR" > /dev/null

  local oidc_worker_url
  oidc_worker_url=$(deploy_and_get_url "$OIDC_APP_DIR" | tail -n1)

  run_terraform_apply "$oidc_worker_url"

  echo "Fetching Terraform outputs..."
  local okta_domain stepup_client_id stepup_client_secret factors_client_id okta_key_id okta_private_key
  okta_domain=$(read_tf_output okta_domain)
  stepup_client_id=$(read_tf_output stepup_client_id)
  stepup_client_secret=$(read_tf_output stepup_client_secret)
  factors_client_id=$(read_tf_output factors_service_client_id)
  okta_key_id=$(read_tf_output okta_key_id)
  okta_private_key=$(read_tf_output okta_private_key)

  echo "Configuring Worker secrets..."
  put_secret "$OIDC_APP_DIR" OKTA_DOMAIN "$okta_domain"
  put_secret "$OIDC_APP_DIR" OKTA_CLIENT_ID "$stepup_client_id"
  put_secret "$OIDC_APP_DIR" OKTA_CLIENT_SECRET "$stepup_client_secret"
  put_secret "$OIDC_APP_DIR" APP_BASE_URL "$oidc_worker_url"

  put_secret "$FACTORS_APP_DIR" OKTA_DOMAIN "$okta_domain"
  put_secret "$FACTORS_APP_DIR" OKTA_MGMT_CLIENT_ID "$factors_client_id"
  put_secret "$FACTORS_APP_DIR" OKTA_MGMT_KID "$okta_key_id"
  put_secret "$FACTORS_APP_DIR" OKTA_MGMT_PRIVATE_KEY "$okta_private_key"

  local factors_worker_url
  factors_worker_url=$(deploy_and_get_url "$FACTORS_APP_DIR" | tail -n1)

  cat <<SUMMARY

Deployment complete!
- OIDC Worker: $oidc_worker_url
- Factors Worker: $factors_worker_url
- No state/temp file was generated by this script.
SUMMARY
}

main "$@"
